### HOSTS
GET http://localhost:3068/admin/host
Content-Type: application/json

### HOST-ADD
POST http://localhost:3068/admin/host-add
Content-Type: application/json

{
   "firstName": "Евгений",
   "secondName": "Ларин"
}

### HOST-UPDATE
POST http://localhost:3068/admin/host-update
Content-Type: application/json

{
   "id": "66032df2183e3929432fd954",
   "avatar": "http://localhost:3068/images/avatar/26032024/183391c5f95349a2_orig.webp"
}